-- Expand name pool from 43 → 100 entries for more variety.
-- First add unique constraint so ON CONFLICT works.
ALTER TABLE public.names ADD CONSTRAINT names_row_num_unique UNIQUE (row_num);

INSERT INTO public.names (row_num, first_name, last_name) VALUES
(44,  'Alexander', 'Parker'),
(45,  'Tyler',     'Evans'),
(46,  'Dylan',     'Edwards'),
(47,  'Aaron',     'Collins'),
(48,  'Nathan',    'Stewart'),
(49,  'Zachary',   'Sanchez'),
(50,  'Adam',      'Morris'),
(51,  'Henry',     'Rogers'),
(52,  'Douglas',   'Reed'),
(53,  'Peter',     'Cook'),
(54,  'Jack',      'Morgan'),
(55,  'Dennis',    'Bell'),
(56,  'Jerry',     'Murphy'),
(57,  'Travis',    'Bailey'),
(58,  'Austin',    'Rivera'),
(59,  'Sean',      'Cooper'),
(60,  'Jesse',     'Richardson'),
(61,  'Bryan',     'Cox'),
(62,  'Vincent',   'Howard'),
(63,  'Russell',   'Ward'),
(64,  'Philip',    'Peterson'),
(65,  'Elijah',    'Gray'),
(66,  'Caleb',     'Ramirez'),
(67,  'Logan',     'James'),
(68,  'Mason',     'Watson'),
(69,  'Ethan',     'Brooks'),
(70,  'Owen',      'Kelly'),
(71,  'Luke',      'Sanders'),
(72,  'Hunter',    'Price'),
(73,  'Liam',      'Bennett'),
(74,  'Noah',      'Wood'),
(75,  'Carter',    'Barnes'),
(76,  'Jayden',    'Ross'),
(77,  'Connor',    'Henderson'),
(78,  'Landon',    'Coleman'),
(79,  'Christian', 'Jenkins'),
(80,  'Cole',      'Perry'),
(81,  'Gabriel',   'Powell'),
(82,  'Isaiah',    'Long'),
(83,  'Cameron',   'Patterson'),
(84,  'Chase',     'Hughes'),
(85,  'Jordan',    'Flores'),
(86,  'Colton',    'Washington'),
(87,  'Tristan',   'Butler'),
(88,  'Marcus',    'Simmons'),
(89,  'Derek',     'Foster'),
(90,  'Dominic',   'Gonzales'),
(91,  'Ian',       'Bryant'),
(92,  'Blake',     'Alexander'),
(93,  'Grant',     'Russell'),
(94,  'Xavier',    'Griffin'),
(95,  'Jared',     'Diaz'),
(96,  'Miles',     'Hayes'),
(97,  'Wesley',    'Myers'),
(98,  'Dakota',    'Ford'),
(99,  'Shane',     'Hamilton'),
(100, 'Tanner',    'Sullivan')
ON CONFLICT (row_num) DO NOTHING;
