-- Seed the names table with 43 first/last name pairs for player generation
-- Original: MySQL Names table with 43 rows

INSERT INTO public.names (row_num, first_name, last_name) VALUES
(1,  'James',    'Smith'),
(2,  'John',     'Johnson'),
(3,  'Robert',   'Williams'),
(4,  'Michael',  'Brown'),
(5,  'David',    'Jones'),
(6,  'William',  'Garcia'),
(7,  'Richard',  'Miller'),
(8,  'Joseph',   'Davis'),
(9,  'Thomas',   'Rodriguez'),
(10, 'Charles',  'Martinez'),
(11, 'Daniel',   'Anderson'),
(12, 'Matthew',  'Taylor'),
(13, 'Anthony',  'Thomas'),
(14, 'Mark',     'Moore'),
(15, 'Donald',   'Jackson'),
(16, 'Steven',   'Martin'),
(17, 'Andrew',   'Lee'),
(18, 'Paul',     'Thompson'),
(19, 'Joshua',   'White'),
(20, 'Kenneth',  'Harris'),
(21, 'Kevin',    'Clark'),
(22, 'Brian',    'Lewis'),
(23, 'George',   'Robinson'),
(24, 'Timothy',  'Walker'),
(25, 'Ronald',   'Young'),
(26, 'Edward',   'Allen'),
(27, 'Jason',    'King'),
(28, 'Jeffrey',  'Wright'),
(29, 'Ryan',     'Scott'),
(30, 'Jacob',    'Torres'),
(31, 'Gary',     'Hill'),
(32, 'Nicholas', 'Green'),
(33, 'Eric',     'Adams'),
(34, 'Jonathan', 'Baker'),
(35, 'Stephen',  'Gonzalez'),
(36, 'Larry',    'Nelson'),
(37, 'Justin',   'Carter'),
(38, 'Scott',    'Mitchell'),
(39, 'Brandon',  'Perez'),
(40, 'Benjamin', 'Roberts'),
(41, 'Samuel',   'Turner'),
(42, 'Raymond',  'Phillips'),
(43, 'Patrick',  'Campbell');
